# -*- coding: utf-8 -*-
"""lab2_3014.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eDdCG0QPJqeschmaSuUMJzqXdbJbElSa
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('teen_phone_addiction_dataset.csv')

df.head(10)

df.info()

df.shape

df.isna().sum()

df.columns

# cols_to_drop = ['ID','Name','Location','Self_Esteem','Addiction_Level','Phone_Usage_Purpose']
# Because oe hot encoding of these will create thousads of columns

df.drop(columns = ['ID','Name','Location', 'Self_Esteem', 'Addiction_Level', 'Phone_Usage_Purpose'], inplace = True)

df.info()

df.shape

df.isna().sum().sum()

df = pd.get_dummies(df, drop_first = True)

df.shape

X=df.drop('Daily_Usage_Hours',axis=1)
y=df['Daily_Usage_Hours']

from sklearn.model_selection import train_test_split
x_train, x_test,y_train,y_test=train_test_split(X,y,test_size=0.3, random_state=2)
# 30% data is tested and 70% trained

# Building the model

from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

# R2 score
model.score(x_test,y_test)

model.score(x_train,y_train)

#l1 regularization
from sklearn import linear_model

lasso_reg = linear_model.Lasso(alpha=.10)
lasso_reg.fit(x_train, y_train)
print(f"Lasso Regression-Training set score: {lasso_reg.score(x_train, y_train):.2f}")
print(f"Lasso Regression-Test set score: {lasso_reg.score(x_test, y_test):.2f}")

from sklearn.linear_model import Ridge
ridge_reg = linear_model.Ridge(alpha=.55)
ridge_reg.fit(x_train, y_train)

print(f"Ridge Regression-Training set score: {ridge_reg.score(x_train, y_train):.2f}")
print(f"Ridge Regression-Test set score: {ridge_reg.score(x_test, y_test):.2f}")

X

df.isna().sum()

df.isna().sum().sum()

df.columns

df.duplicated().sum()

# no null and duplicated values
# No need of handling

# Outlier detection using boxplots for  numeric data
df.columns
for i in df.columns:
    if df[i].dtype!='object':
        sns.boxplot(df[i])
        plt.xlabel(i)
        plt.ylabel('range')
        plt.title(i)
        plt.show()

df.shape

df.columns

# Removing Outliers
col=['Daily_Usage_Hours', 'Exercise_Hours', 'Screen_Time_Before_Bed', 'Weekend_Usage_Hours']
for i in col:
    Q1=df[i].quantile(0.25)
    Q3=df[i].quantile(0.75)
    IQR=Q3-Q1
    LF=Q1-1.5*IQR
    UF=Q3+1.5*IQR
    df=df[(df[i]>=LF) & (df[i]<=UF)]

df.shape