# -*- coding: utf-8 -*-
"""lab8_3014.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nJstqXI__JtI_LO-gvC7Fn5min2I9qEo
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import numpy as np
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import warnings
warnings.filterwarnings("ignore")

X=10*np.random.rand(250,2)
print(X.shape)
kmean=KMeans(n_clusters=3)
kmean.fit(X)
kmean.cluster_centers_

labels=kmean.labels_
print(labels)

silhouette_avg = silhouette_score(X, labels)
print(f"Silhouette Score: {silhouette_avg}")

wcss = []
for i in range(1,20):
 kmeans = KMeans(n_clusters=i,init='k-means++',max_iter=300,n_init=10,random_state=0)
 kmeans.fit(X)
 wcss.append(kmeans.inertia_)
 print("Cluster", i, "Inertia", kmeans.inertia_)
plt.plot(range(1,20),wcss)
plt.title('The Elbow Curve')
plt.xlabel('Number of clusters')
plt.ylabel('WCSS') ##WCSS stands for total within-cluster sum of square
plt.show()

n_clusters = 4 # number of clusters
kmeans = KMeans(n_clusters=n_clusters, random_state=42)
labels = kmeans.fit_predict(X)
print(labels)

silhouette_avg = silhouette_score(X, labels)
print(f"Silhouette Score: {silhouette_avg}")

print("\nCluster Centroids:")
for i, centroid in enumerate(kmeans.cluster_centers_):
    print(f"Centroid {i}: {centroid}")

centroids=kmeans.cluster_centers_
 # Plotting the data points colored by cluster
plt.figure(figsize=(8, 6))
plt.scatter(X[:, 0], X[:, 1], c=labels, cmap='viridis', s=50, alpha=0.8)

 # Plotting centroids
plt.scatter(centroids[:, 0], centroids[:, 1], c='red', marker='X', s=200, label='Centroids')

plt.title('K-Means Clustering')
plt.xlabel('Feature 1')
plt.ylabel('Feature 2')
plt.legend()
plt.grid(True)
plt.show()

for n_cluster in range(2,10):
 kmeans = KMeans(n_clusters=n_cluster, random_state=42)
 cluster_labels = kmeans.fit_predict(X)
 silhouette_avg = silhouette_score(X, cluster_labels)
 print(f"clusters:{n_cluster}, Silhouette Score: {silhouette_avg}")

range_n_clusters = [2, 3, 4, 5, 6, 7,8 ,9,10]
silhouette_avg = []
for num_clusters in range_n_clusters:

 # initialise kmeans
 kmeans = KMeans(n_clusters=num_clusters)
 kmeans.fit(X)
 cluster_labels = kmeans.labels_

 # silhouette score
 silhouette_avg.append(silhouette_score(X, cluster_labels))
plt.plot(range_n_clusters,silhouette_avg,'bx-')
plt.xlabel('Values of K')
plt.ylabel('Silhouette score')
plt.title('Silhouette analysis For Optimal k')
plt.show()

# printing score for k's best value
print(f"Silhouette Score: {silhouette_avg[2]}")

