# -*- coding: utf-8 -*-
"""lab1_3014.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MehYWbzF8LjiLkOrQqbE4ITYzL0RX-gY
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('college_student_placement_dataset.csv')

df.head()

df.info()

df.shape

df.isna().sum()

df.isna().sum().sum()

df.dropna(inplace=True)

df.shape

df.duplicated().sum()

df.columns
for i in df.columns:
    print(df[i].dtype)

for i in df.columns:
    if df[i].dtype != 'object':
        sns.boxplot(df[i])
        plt.xlabel(i)
        plt.ylabel('range')
        plt.title(i)
        plt.show()

col = ['IQ']
for i in col:
    Q1=df[i].quantile(0.25)
    Q3=df[i].quantile(0.75)
    IQR=Q3-Q1
    LF=Q1-1.5*IQR
    UF=Q3+1.5*IQR
    df=df[(df[i]>=LF) & (df[i]<=UF)]

df.shape

from scipy import stats
import numpy as np
z = np.abs(stats.zscore(df['IQ']))
print(z)

# identifying outliers
threshold = 3
print(df[z > threshold])

col2=[]
for i in df.columns:
    if (df[i].dtype!='object'):
        col2.append(i)
col2

from statsmodels.stats.outliers_influence import variance_inflation_factor
X=df[col2]  # Storing data of independent numeric columns in x
X
vif_data=pd.DataFrame()
vif_data['Features']=X.columns

vif_data['VIF Values']=[variance_inflation_factor(X.values,i) for i in  range(len(X.columns))]
vif_data

Y=df['CGPA']

from sklearn.model_selection import train_test_split
x_train, x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2, random_state=0)

x_train.shape

y_train

y_test

from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)
y_pred

from sklearn.metrics import *
r2_score(y_test,y_pred)

#regression line aigns with data

