# -*- coding: utf-8 -*-
"""3014_Lab3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10LENEQhfnkFVmM8qFp35H5vsM2ycOOAQ
"""

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

data = pd.read_csv('college_student_placement_dataset.csv')

data.head()

data.dtypes

data.isnull().sum()

data = pd.get_dummies(data, columns=['Internship_Experience', 'Placement'], drop_first=True)

data.isnull().sum(axis = 1).sum()

data.duplicated().sum()

data = data.drop(columns=['College_ID'])

data.columns

data.dtypes

# removing outliers from numerical columns

# Create an empty boolean mask that will identify the rows to keep
combined_mask = pd.Series([True] * len(data), index=data.index)

# Get numerical columns
numerical_cols = data.select_dtypes(include=np.number).columns

for i in numerical_cols:
    q1 = np.percentile(data[i], 25)
    q3 = np.percentile(data[i], 75)
    iqr = q3-q1
    LB = q1 - 1.5*iqr
    UB = q3 + 1.5*iqr
    col_mask = (data[i] > LB) & (data[i] < UB)
    combined_mask = combined_mask & col_mask

data = data[combined_mask]

data.shape

# we lost 85 rows from outliers removal

X = data.drop(columns='Placement_Yes')
y = data['Placement_Yes']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.15, random_state = 42)

# Standardizing the data

## Applying logistic regression
log_reg = LogisticRegression(max_iter=700)
log_reg.fit(X_train, y_train)

y_pred = log_reg.predict(X_test)
y_pred

accuracy_score(y_test, y_pred)

from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix

print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(f1_score(y_test, y_pred))
confusion_matrix(y_test, y_pred)

# standard scaler standardization
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

X_train = pd.DataFrame(X_train)
X_train

X_test = pd.DataFrame(X_test)
X_test

# MinMax scaler
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

X_train = pd.DataFrame(X_train)
X_train

log_reg = LogisticRegression(max_iter = 650)
log_reg.fit(X_train, y_train)
y_pred = log_reg.predict(X_test)
accuracy_score(y_test, y_pred)

